version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/project1"
      - "/project2"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Tokyo"
