version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/project1"
      - "/project2"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
