name: 'Secret Test'

on:
  workflow_dispatch:

jobs:
  jobA:
    runs-on: ubuntu-latest
    outputs:
      a_out: ${{ steps.secret_output.outputs.a_out }}
    steps:
      - name: Secret Output
        id: secret_output
        run: |
          echo "JobA Secret ${{ secrets.SAMPLE_SECRET }}"
          echo "a_out=hogefuga" >> $GITHUB_OUTPUT
          
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - name: Get Secret from Job A
        run: |
          echo "Secret: ${{ needs.jobA.outputs.a_out }}"
