name: 'Secret Test'

on:
  workflow_dispatch:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Some
        run: |
          echo "This is job A"
          echo "Secret: ${{ secrets.SAMPLE_SECRET }}"
